sudo: false
language: scala

scala:
  - 2.12.6

jdk:
  - oraclejdk8

# microsites
before_install:
  - export PATH=${PATH}:./vendor/bundle

# microsites
install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "c-block/jbok" && test $TRAVIS_SCALA_VERSION == "2.12.4" && sbt docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
    - $HOME/.rvm/
    - vendor/bundle

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete